name: Bump Installation Scripts

on:
  push:
    tags:
      - v*

permissions:
  contents: write

jobs:
  update-version-references:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Get pushed tag
        id: get_version
        run: |
          # Extract the tag name from the GitHub ref
          TAG_NAME=${GITHUB_REF#refs/tags/}
          echo "LATEST_TAG=${TAG_NAME}" >> $GITHUB_ENV
          echo "Using tag: ${TAG_NAME}"

      - name: Update version in PowerShell install script
        run: |
          sed -i "s/\$DefaultVersion = \".*\"/\$DefaultVersion = \"${LATEST_TAG}\"/" scripts/install.ps1
          echo "Updated version in scripts/install.ps1 to ${LATEST_TAG}"

      - name: Update version in Bash install script
        run: |
          sed -i "s/DEFAULT_VERSION=\".*\"/DEFAULT_VERSION=\"${LATEST_TAG}\"/" scripts/install.sh
          echo "Updated version in scripts/install.sh to ${LATEST_TAG}"

      - name: Commit and push changes
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

          git add scripts/install.ps1 scripts/install.sh

          # Only commit if there are changes
          if git diff --staged --quiet; then
            echo "No changes to commit"
            exit 0
          fi

          git commit -m "Update version references to ${LATEST_TAG}"
          git push origin HEAD:main
